default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_weather_development
  username: postgres
  password: postgres
  host: rails_weather-db-1
  port: 5432

test:
  <<: *default
  database: rails_weather_test
  username: postgres
  password: postgres
  host: rails_weather-db-1
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: rails_weather_production
    username: rails_weather
    password: <%= ENV["RAILS_WEATHER_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_weather_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_weather_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_weather_production_cable
    migrations_paths: db/cable_migrate
